service infra-airflow: running

diff --git a/services/batch_layer/deployment-airflow-service.yaml b/services/batch_layer/deployment-airflow-service.yaml
--- a/services/batch_layer/deployment-airflow-service.yaml
+++ b/services/batch_layer/deployment-airflow-service.yaml
@@ -1,13 +1,9 @@
 ---
-x-airflow-common:
-  &airflow-common
-  # In order to add custom dependencies or upgrade provider packages you can use your extended image.
-  # Comment the image line, place your Dockerfile in the directory where you placed the docker-compose.yaml
-  # and uncomment the "build" line below, Then run `docker-compose build` to build the images.
+version: '3.8'
+
+x-airflow-common: &airflow-common
   image: ${AIRFLOW_IMAGE_NAME:-apache/airflow:2.7.2}
-  # build: .
-  environment:
-    &airflow-common-env
+  environment: &airflow-common-env
     AIRFLOW__CORE__EXECUTOR: CeleryExecutor
     AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
     AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
@@ -25,122 +21,192 @@ x-airflow-common:
     - ../../mnt/airflow/dags:/opt/airflow/dags
     - ../../mnt/airflow/logs:/opt/airflow/logs
     - ../../mnt/airflow/plugins:/opt/airflow/plugins
-    - .env:/opt/airflow/env/.env
+    - /env/.env:/opt/airflow/env/.env
     - /var/run/docker.sock:/var/run/docker.sock
   user: "${AIRFLOW_UID:-50000}:0"
-
 
 services:
   postgres:
     image: postgres:13
+    networks:
+      - hadoop_network
     environment:
       POSTGRES_USER: airflow
       POSTGRES_PASSWORD: airflow
       POSTGRES_DB: airflow
     volumes:
       - postgres-db-volume:/var/lib/postgresql/data
+    healthcheck:
+      test: [ "CMD-SHELL", "pg_isready -U airflow" ]
+      interval: 10s
+      timeout: 5s
+      retries: 5
     restart: always
 
   redis:
     image: redis:latest
+    networks:
+      - hadoop_network
     expose:
       - 6379
+    healthcheck:
+      test: [ "CMD", "redis-cli", "ping" ]
+      interval: 10s
+      timeout: 5s
+      retries: 5
     restart: always
 
   airflow-webserver:
     <<: *airflow-common
     command: webserver
-    user: "${AIRFLOW_UID:-50000}:0"
+    networks:
+      - hadoop_network
     ports:
       - 8080:8080
-    restart: always
-
+    deploy:
+      replicas: 1
+      restart_policy:
+        condition: on-failure
+        delay: 5s
+        max_attempts: 3
 
   airflow-scheduler:
     <<: *airflow-common
     command: scheduler
-    user: "${AIRFLOW_UID:-50000}:0"
-    restart: always
+    networks:
+      - hadoop_network
+    deploy:
+      replicas: 1
+      restart_policy:
+        condition: on-failure
+        delay: 5s
+        max_attempts: 3
 
   airflow-worker:
     <<: *airflow-common
     command: celery worker
-    user: "${AIRFLOW_UID:-50000}:0"
+    networks:
+      - hadoop_network
     environment:
       <<: *airflow-common-env
       DUMB_INIT_SETSID: "0"
-    restart: always
+    deploy:
+      replicas: 2
+      restart_policy:
+        condition: on-failure
+        delay: 5s
+        max_attempts: 3
 
   airflow-triggerer:
     <<: *airflow-common
+    networks:
+      - hadoop_network
     command: triggerer
-    user: "${AIRFLOW_UID:-50000}:0"
     restart: always
 
+#  airflow-init:
+#    <<: *airflow-common
+#    networks:
+#      - hadoop_network
+#    entrypoint: /bin/bash
+#    command:
+#      - -c
+#      - |
+#        function ver() {
+#          printf "%04d%04d%04d%04d" $${1//./ }
+#        }
+#        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
+#        airflow_version_comparable=$$(ver $${airflow_version})
+#        min_airflow_version=2.2.0
+#        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+#        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+#          echo
+#          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
+#          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
+#          echo
+#          exit 1
+#        fi
+#        if [[ -z "${AIRFLOW_UID}" ]]; then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
+#          echo "If you are on Linux, you SHOULD follow the instructions below to set "
+#          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
+#          echo "For other operating systems you can get rid of the warning with manually created .env file:"
+#          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
+#          echo
+#        fi
+#        one_meg=1048576
+#        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+#        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+#        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+#        warning_resources="false"
+#        if (( mem_available < 4000 )) ; then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
+#          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
+#          echo
+#          warning_resources="true"
+#        fi
+#        if (( cpus_available < 2 )); then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
+#          echo "At least 2 CPUs recommended. You have $${cpus_available}"
+#          echo
+#          warning_resources="true"
+#        fi
+#        if (( disk_available < one_meg * 10 )); then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
+#          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
+#          echo
+#          warning_resources="true"
+#        fi
+#        if [[ $${warning_resources} == "true" ]]; then
+#          echo
+#          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
+#          echo "Please follow the instructions to increase amount of resources available:"
+#          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
+#          echo
+#        fi
+#        mkdir -p /sources/logs /sources/dags /sources/plugins
+#        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+#
+#        # Executa o upgrade do banco de dados
+#        airflow db upgrade
+#
+#        # Verifica a versão do Airflow
+#        exec /entrypoint airflow version
+#    environment:
+#      <<: *airflow-common-env
+#      AIRFLOW_UID: 50000
+#      _AIRFLOW_DB_UPGRADE: 'true'
+#      _AIRFLOW_WWW_USER_CREATE: 'true'
+#      _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
+#      _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
+#      _PIP_ADDITIONAL_REQUIREMENTS: ''
+#    volumes:
+#      - ${AIRFLOW_PROJ_DIR:-.}:/sources
+#    deploy:
+#      restart_policy:
+#        condition: none
   airflow-init:
     <<: *airflow-common
+    networks:
+      - hadoop_network
     entrypoint: /bin/bash
     command:
       - -c
       - |
-        function ver() {
-          printf "%04d%04d%04d%04d" $${1//./ }
-        }
-        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && gosu airflow airflow version)
-        airflow_version_comparable=$$(ver $${airflow_version})
-        min_airflow_version=2.2.0
-        min_airflow_version_comparable=$$(ver $${min_airflow_version})
-        if (( airflow_version_comparable < min_airflow_version_comparable )); then
-          echo
-          echo -e "\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m"
-          echo "The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!"
-          echo
-          exit 1
-        fi
-        if [[ -z "${AIRFLOW_UID}" ]]; then
-          echo
-          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m"
-          echo "If you are on Linux, you SHOULD follow the instructions below to set "
-          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root."
-          echo "For other operating systems you can get rid of the warning with manually created .env file:"
-          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user"
-          echo
-        fi
-        one_meg=1048576
-        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
-        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
-        disk_available=$$(df / | tail -1 | awk '{print $$4}')
-        warning_resources="false"
-        if (( mem_available < 4000 )) ; then
-          echo
-          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m"
-          echo "At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))"
-          echo
-          warning_resources="true"
-        fi
-        if (( cpus_available < 2 )); then
-          echo
-          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m"
-          echo "At least 2 CPUs recommended. You have $${cpus_available}"
-          echo
-          warning_resources="true"
-        fi
-        if (( disk_available < one_meg * 10 )); then
-          echo
-          echo -e "\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m"
-          echo "At least 10 GBs recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))"
-          echo
-          warning_resources="true"
-        fi
-        if [[ $${warning_resources} == "true" ]]; then
-          echo
-          echo -e "\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m"
-          echo "Please follow the instructions to increase amount of resources available:"
-          echo "   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin"
-          echo
-        fi
-        mkdir -p /sources/logs /sources/dags /sources/plugins
-        chown -R "${AIRFLOW_UID}:0" /sources/{logs,dags,plugins}
+        # Verifica se o PostgreSQL está pronto
+        until pg_isready -h postgres -U airflow; do
+          echo "Waiting for PostgreSQL to be ready..."
+          sleep 2
+        done
+
+        # Executa o upgrade do banco de dados
+        airflow db upgrade
+
+        # Verifica a versão do Airflow
         exec /entrypoint airflow version
     environment:
       <<: *airflow-common-env
@@ -150,13 +216,16 @@ services:
       _AIRFLOW_WWW_USER_USERNAME: ${_AIRFLOW_WWW_USER_USERNAME:-airflow}
       _AIRFLOW_WWW_USER_PASSWORD: ${_AIRFLOW_WWW_USER_PASSWORD:-airflow}
       _PIP_ADDITIONAL_REQUIREMENTS: ''
-    user: "${AIRFLOW_UID:-50000}:0"
     volumes:
       - ${AIRFLOW_PROJ_DIR:-.}:/sources
+    deploy:
+      restart_policy:
+        condition: none
 
   airflow-cli:
     <<: *airflow-common
-    user: "${AIRFLOW_UID:-50000}:0"
+    networks:
+      - hadoop_network
     environment:
       <<: *airflow-common-env
       CONNECTION_CHECK_MAX_COUNT: "0"
@@ -167,16 +236,15 @@ services:
 
   flower:
     <<: *airflow-common
+    networks:
+      - hadoop_network
     command: celery flower
-    user: "${AIRFLOW_UID:-50000}:0"
     ports:
       - 5555:5555
     restart: always
 
-
 volumes:
   postgres-db-volume:
-
 
 networks:
   hadoop_network:
